name: GameModeUI
version: 0.0.1
main: DavyCraft648\GameModeUI\Main
api: 3.0.0
website: https://github.com/DavyCraft648/GamemodeUI
description: Select your gamemode
author: DavyCraft648
commands:
  gamemodeui:
    description: Change your gamemode
    aliases:
      - gmui
    permission: gamemodeui.form
    permission-message: "§cYou do not have permission to use this command!"
permissions:
  gamemodeui.form:
    default: op
  gamemodeui.reload:
    default: op
  gamemodeui.survival:
    default: op
  gamemodeui.creative:
    default: op
  gamemodeui.adventure:
    default: op
  gamemodeui.spectator:
    default: op
