--- # GamemodeUI plugin configuration file

#-------------------------------
# Do not change this
configVersion: GameModeUI v0.0.1
#-------------------------------

menu:
  titleForm: "GameModeUI"
  descriptionForm: "&aSelect to change your Gamemode"

notPlayer: "&cUse this command in-game!"

exit:
  message: "&aExiting GameModeUI"
  button:
    name: "&cExit"
  image:
    type: 0
    path: "textures/ui/cancel"

survival:
  message: "&eSet your own gamemode to Survival mode"
  button:
    name: "Survival"
  image:
    type: 0
    path: "textures/ui/icon_deals"

creative:
  message: "&eSet your own gamemode to Creative mode"
  button:
    name: "Creative"
  image:
    type: 0
    path: "textures/ui/creative_icon"

spectator:
  message: "&eSet your own gamemode to Spectator mode"
  button:
    name: "Spectator"
  image:
    type: 0
    path: "textures/ui/icon_balloon"

adventure:
  message: "&eSet your own gamemode to Adventure mode"
  button:
    name: "Adventure"
  image:
    type: 0
    path: "textures/ui/icon_minecoin_9x9"
...
