---
#  _____
# |  __ \
# | |  | | __ _ __   __ _   _
# | |  | |/ _` |\ \ / /| | | |
# | |__| | (_| | \ V / | |_| |
# |_____/ \__,_|  \_/   \__, |
#        Craft648        __/ |
#    Ini File Config    |___/
config-version: 1
#^^^^^^^^^^^^^^^^
#config-version: 1 jangan diganti yak!

menu:
  title-form: GameModeUI #Judul Dari Form GamemodeUI
  description-form: Pilih untuk ubah Gamemode #Deskripsi Dari Form GamemodeUI
  new: true
# new: true  (UI baru)
# new: false (UI lama)

exit:
  msg: §eKeluar Dari GamemodeUI #Pesan Saat Keluar dari Menu *kadang ga work untuk ui lama
  console: §4Gunakan Command Dalam Game! #Pesan saat Command Digunakan oleh Console
  noperm: §cKamu Ga Punya Perm untuk Bisa Menggunakan Command ini #Pesan Jika Player Ga Punya Permission Command
  nopermgm: §4Kamu Ga Punya Perm untuk Bisa Mengganti Gamemode #Pesan Jika Player Ga Punya Permission Gamemode
  button:
    cancel: "§l§o§4Batalkan§r \n§r§o§fKlik untuk keluar" #Nama Tombol Keluar (UI baru)
    name: Keluar #Nama Tombol Keluar (UI lama)
    image: textures/ui/cancel #Gambar Tombol Keluar
survival:
  title: §9Mode Survival #Title Survival
  subtitle: §bMengubah ke Mode Survival #Subtitle Survival
  msg: §eMengubah ke Mode Survival #Pesan Survival
  button:
    name: Survival #Nama Tombol Survival
creative:
  title: §9Mode Creative #Title Creative
  subtitle: §bMengubah ke Mode Creative #Subtitle Creative
  msg: §eMengubah ke Mode Creative #Pesan Creative
  button:
    name: Creative #Nama Tombol Creative
spectator:
  title: §9Mode Spectator #Title Spectator
  subtitle: §bMengubah ke Mode Spectator #Subtitle Spectator
  msg: §eMengubah ke Mode Spectator #Pesan Spectator
  button:
    name: Spectator #Nama Tombol Spectator
adventure:
  title: §9Mode Adventure #Title Adventure
  subtitle: §bMengubah ke Mode Adventure #Subtitle Adventure
  msg: §eMengubah ke Mode Adventure #Pesan Adventure
  button:
    name: Adventure #Nama Tombol Adventure
...
